const CDN = "https://booking-paraisoencantado.up.railway.app/images";

// 13 Habitaciones reales — Paraíso Encantado
export const rooms = [
  {
    id: "jungla",
    name: "Jungla",
    type: "Suite Master",
    description: "Privacidad total rodeada de selva. Cama King + matrimonial, terraza panorámica y piscina spa entre los helechos.",
    bedType: "King + Matrimonial",
    maxGuests: 4,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Piscina spa privada", "Terraza panorámica", "Vistas a la selva", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/JUNGLA.jpg`,
    images: [
      `${CDN}/JUNGLA/PORTADA.jpg`,
      `${CDN}/JUNGLA/DSCF1065.jpg`,
      `${CDN}/JUNGLA/DSCF1078.jpg`,
      `${CDN}/JUNGLA/DSCF1094.jpg`,
    ],
  },
  {
    id: "suite-lajas",
    name: "Suite Lajas",
    type: "Suite Standard",
    description: "Elegancia natural con vistas a la sierra. Terraza privada y acceso directo a la naturaleza huasteca.",
    bedType: "King",
    maxGuests: 4,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Terraza privada", "Vistas a la sierra", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/LAJAS.jpg`,
    images: [
      `${CDN}/LAJAS/PORTADA.jpg`,
      `${CDN}/LAJAS/Copia de DSC09589-HDR.jpg`,
      `${CDN}/LAJAS/Copia de DSC09610-HDR.jpg`,
      `${CDN}/LAJAS/Copia de DSC09615.jpg`,
    ],
  },
  {
    id: "suite-lindavista",
    name: "Suite LindaVista",
    type: "Suite Master",
    description: "Las mejores vistas panorámicas a la Sierra Gorda desde tu terraza privada. Un amanecer aquí lo cambia todo.",
    bedType: "King",
    maxGuests: 4,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Terraza panorámica", "Vistas 360°", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/LV.jpg`,
    images: [
      `${CDN}/LINDAVISTA/PORTADA.jpg`,
      `${CDN}/LINDAVISTA/Copia de DSC09539-HDR.jpg`,
      `${CDN}/LINDAVISTA/Copia de DSC09569.jpg`,
      `${CDN}/LINDAVISTA/Copia de DSC09576.jpg`,
    ],
  },
  {
    id: "suite-flor-de-liz-1",
    name: "Suite Flor de Liz 1",
    type: "Suite Plus",
    description: "Amplios espacios con elegancia natural, terraza y entorno selvático. Perfecta para desconectarse en pareja o familia.",
    bedType: "King",
    maxGuests: 4,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Terraza", "Jardín privado", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/FDL.jpg`,
    images: [
      `${CDN}/FLOR DE LIS 1/PORTADA.jpg`,
      `${CDN}/FLOR DE LIS 1/Copia de DSC09450-2.jpg`,
      `${CDN}/FLOR DE LIS 1/Copia de DSC09677-HDR.jpg`,
      `${CDN}/FLOR DE LIS 1/DSCF1191.jpg`,
    ],
  },
  {
    id: "suite-flor-de-liz-2",
    name: "Suite Flor de Liz 2",
    type: "Suite Plus",
    description: "Hermana de la Suite Flor de Liz 1, con su propio carácter y vistas únicas a la vegetación huasteca.",
    bedType: "King",
    maxGuests: 4,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Terraza", "Jardín privado", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/FDL2.jpg`,
    images: [
      `${CDN}/FLOR DE LIS 2/PORTADA.jpeg`,
      `${CDN}/FLOR DE LIS 2/Copia de DSC09450-2.jpg`,
      `${CDN}/FLOR DE LIS 2/Copia de DSC09677-HDR.jpg`,
    ],
  },
  {
    id: "helechos-1",
    name: "Helechos 1",
    type: "Suite Familiar",
    description: "Suite ideal para familias con espacios generosos, jardín privado y vista a los helechos gigantes de la selva.",
    bedType: "King + Literas",
    maxGuests: 6,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Jardín privado", "Literas", "Terraza", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/HEL1.jpg`,
    images: [
      `${CDN}/HELECHOS 1/PORTADA.jpg`,
      `${CDN}/HELECHOS 1/Copia de DSC09461-HDR 2.jpg`,
      `${CDN}/HELECHOS 1/Copia de DSC09516-HDR.jpg`,
      `${CDN}/HELECHOS 1/Copia de DSC09526-HDR.jpg`,
    ],
  },
  {
    id: "helechos-2",
    name: "Helechos 2",
    type: "Suite Familiar Plus",
    description: "La versión ampliada de Helechos, con mayor capacidad y todos los lujos para una familia completa.",
    bedType: "King + Literas",
    maxGuests: 6,
    extraPersonPrice: 500,
    price: 1900,
    amenities: ["Jardín privado", "Literas", "Terraza amplia", "Estacionamiento propio", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/HEL2.jpg`,
    images: [
      `${CDN}/HELECHOS 2/PORTADA.jpg`,
      `${CDN}/HELECHOS 2/Copia de DSC09461-HDR.jpg`,
      `${CDN}/HELECHOS 2/Copia de DSC09556-HDR.jpg`,
    ],
  },
  {
    id: "lirios-1",
    name: "Lirios 1",
    type: "Standard",
    description: "Confort con carácter, rodeada de lirios tropicales. La opción perfecta para parejas que buscan autenticidad.",
    bedType: "Matrimonial",
    maxGuests: 4,
    extraPersonPrice: 400,
    price: 1500,
    amenities: ["Baño privado", "Terraza", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/LIRIOS1.jpg`,
    images: [
      `${CDN}/LIRIOS 1/PORTADA.jpg`,
      `${CDN}/LIRIOS 1/Copia de DSC09524-HDR.jpg`,
      `${CDN}/LIRIOS 1/Copia de DSCF1620.jpg`,
      `${CDN}/LIRIOS 1/Copia de DSCF1622.jpg`,
    ],
  },
  {
    id: "lirios-2",
    name: "Lirios 2",
    type: "Standard Plus",
    description: "Versión mejorada de Lirios, con espacios más amplios y detalles adicionales de confort en plena naturaleza.",
    bedType: "Matrimonial",
    maxGuests: 4,
    extraPersonPrice: 400,
    price: 1500,
    amenities: ["Baño privado", "Terraza", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/LIRIOS2.jpg`,
    images: [
      `${CDN}/LIRIOS 2/PORTADA.jpg`,
      `${CDN}/LIRIOS 2/Copia de DSC09483-HDR.jpg`,
      `${CDN}/LIRIOS 2/Copia de DSC09489-2.jpg`,
    ],
  },
  {
    id: "orquideas-2",
    name: "Orquídeas 2",
    type: "Superior King",
    description: "Habitación de diseño íntimo para dos, entre orquídeas silvestres y el sonido constante de la selva.",
    bedType: "King",
    maxGuests: 2,
    extraPersonPrice: 0,
    price: 1500,
    amenities: ["Baño privado", "Ducha", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/ORQ.jpg`,
    images: [
      `${CDN}/ORQUIDEAS 2/PORTADA.jpg`,
      `${CDN}/ORQUIDEAS 2/Copia de DSC09568-HDR.jpg`,
      `${CDN}/ORQUIDEAS 2/DSCF1607.jpg`,
    ],
  },
  {
    id: "orquideas-3",
    name: "Orquídeas 3",
    type: "Superior King",
    description: "Similar a Orquídeas 2, con su propia perspectiva del jardín y la selva. Ideal para una escapada íntima.",
    bedType: "King",
    maxGuests: 2,
    extraPersonPrice: 0,
    price: 1500,
    amenities: ["Baño privado", "Ducha", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/ORQ.jpg`,
    images: [
      `${CDN}/ORQUIDEAS 3/PORTADA.jpg`,
      `${CDN}/ORQUIDEAS 3/Copia de DSC09567-HDR.jpg`,
      `${CDN}/ORQUIDEAS 3/Copia de DSC09568-HDR.jpg`,
      `${CDN}/ORQUIDEAS 3/DSCF1612.jpg`,
    ],
  },
  {
    id: "orquideas-doble",
    name: "Orquídeas Doble",
    type: "Superior King",
    description: "La más espaciosa de las Orquídeas. Perfecta para parejas que desean más espacio sin renunciar a la intimidad.",
    bedType: "King",
    maxGuests: 2,
    extraPersonPrice: 0,
    price: 1500,
    amenities: ["Baño privado amplio", "Ducha", "Terraza", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/ORQ4.jpg`,
    images: [
      `${CDN}/ORQUIDEAS DOBLE/PORTADA.jpg`,
      `${CDN}/ORQUIDEAS DOBLE/Copia de DSC09602-HDR.jpg`,
      `${CDN}/ORQUIDEAS DOBLE/Copia de DSCF1616.jpg`,
      `${CDN}/ORQUIDEAS DOBLE/Copia de DSCF1617.jpg`,
    ],
  },
  {
    id: "bromelias",
    name: "Bromelias",
    type: "Standard Plus",
    description: "Rodeada de bromelias tropicales en equilibrio con la naturaleza. Confort genuino en el corazón de la selva.",
    bedType: "Matrimonial",
    maxGuests: 4,
    extraPersonPrice: 400,
    price: 1500,
    amenities: ["Baño privado", "Terraza", "Jardín", "Estacionamiento", "Aire acondicionado", "WiFi"],
    cover: `${CDN}/BROM1.jpg`,
    images: [
      `${CDN}/BROMELIAS 1/PORTADA.jpg`,
      `${CDN}/BROMELIAS 1/Copia de DSC09385-HDR.jpg`,
      `${CDN}/BROMELIAS 1/Copia de DSC09419-HDR.jpg`,
      `${CDN}/BROMELIAS 1/Copia de DSC09431.jpg`,
    ],
  },
];

// Amenidades principales
export const amenities = [
  {
    id: "piscina-spa",
    name: "Piscina Spa",
    icon: "droplet",
    description: "Piscina spa con agua caliente entre los helechos. El silencio de la selva como música de fondo.",
  },
  {
    id: "restaurante",
    name: "El Papán Huasteco",
    icon: "utensils",
    description: "Zacahuiles, bocoles y mole huasteco hechos en comal cada mañana. Cocina de raíz potosina.",
  },
  {
    id: "wifi",
    name: "WiFi de Alta Velocidad",
    icon: "wifi",
    description: "Fibra óptica en todo el hotel para quienes necesitan estar conectados — o desconectarse cuando quieran.",
  },
  {
    id: "estacionamiento",
    name: "Estacionamiento Privado",
    icon: "car",
    description: "Estacionamiento propio frente a cada habitación. Sin cuotas, sin preocupaciones.",
  },
  {
    id: "tours",
    name: "Tours Ecoturísticos",
    icon: "map",
    description: "Pozas Tamul, Cascada de Micos, El Jardín Surrealista. Organizamos tu experiencia completa en la Huasteca.",
  },
  {
    id: "spa",
    name: "Spa & Masajes",
    icon: "leaf",
    description: "Masajes relajantes con aceites naturales de la región. El complemento perfecto después de explorar la selva.",
  },
  {
    id: "naturista",
    name: "Yoga & Meditación",
    icon: "sun",
    description: "Clases al amanecer en nuestra plataforma natural. La selva potosina como tu estudio.",
  },
  {
    id: "botanica",
    name: "Jardín Botánico",
    icon: "flower",
    description: "Acceso libre a nuestra colección de flora endémica de la Huasteca. Un museo vivo.",
  },
];

// Info del Hotel
export const hotelInfo = {
  name: "Paraíso Encantado",
  tagline: "Donde la selva te recibe.",
  description: "Hotel boutique de lujo en Xilitla, Huasteca Potosina. A pasos del Jardín Surrealista de Edward James.",
  location: {
    city: "Xilitla, San Luis Potosí",
    address: "Carretera a Xilitla, Huasteca Potosina",
    coordinates: {
      lat: 21.3896,
      lng: -98.9955,
    },
  },
  contact: {
    phone: "+52 489 100 7679",
    email: "reservas@paraisoencantado.com",
    whatsapp: "+52 489 100 7679",
  },
  hours: {
    checkIn: "15:00",
    checkOut: "12:00",
    reception: "24/7",
  },
  totalRooms: 13,
  yearOpened: 2020,
  heroImage: `${CDN}/PRINCIPAL.jpg`,
  features: [
    "Piscina spa privada en suites selectas",
    "Restaurante El Papán Huasteco",
    "Vistas panorámicas a la Sierra Gorda",
    "A 7 min del Jardín de Edward James",
    "WiFi de fibra óptica",
    "Estacionamiento privado gratuito",
    "Servicios de spa y masajes",
    "Tours ecoturísticos organizados",
  ],
};

// Testimonios reales
export const testimonials = [
  {
    author: "Presidente de México",
    source: "Visita oficial a Xilitla",
    text: "Despertamos en el cielo.",
    rating: 5,
  },
  {
    author: "Visitante internacional",
    source: "Google — reseña verificada",
    text: "La experiencia más auténtica que he tenido en México. La selva, la comida, el servicio... todo es extraordinario.",
    rating: 5,
  },
  {
    author: "Pareja en luna de miel",
    source: "Google — reseña verificada",
    text: "El lugar perfecto para reconectar. Cada mañana despertábamos con el canto de los tucanes. Volveremos.",
    rating: 5,
  },
];

// Información del Restaurante
export const restaurantInfo = {
  name: "El Papán Huasteco",
  description: "Cocina huasteca de raíz, con tortillas en comal esa mañana y recetas que han alimentado a la región por siglos.",
  hours: {
    breakfast: "07:00 — 10:30",
    lunch: "13:00 — 16:00",
    dinner: "18:30 — 21:30",
  },
  specialties: [
    "Zacahuil huasteco",
    "Bocoles con frijoles negros",
    "Mole de olla potosino",
    "Mixiotes de pollo",
    "Enchiladas huastecas",
    "Agua de jamaica y horchata fresca",
  ],
};
