// 15 Habitaciones - Paraiso Encantado
export const rooms = [
  {
    id: "jungla",
    name: "Suite Jungla",
    type: "Suite Master",
    description: "Santuario de privacidad absoluta con piscina privada, terraza panorámica y vistas a la selva",
    bedType: "King + Matrimonial",
    maxGuests: 4,
    price: 2000,
    amenities: ["Piscina privada", "Terraza", "Vistas a la selva", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/JUNGLA/1.jpg",
      "/images/rooms/JUNGLA/2.jpg",
      "/images/rooms/JUNGLA/3.jpg",
    ],
  },
  {
    id: "bosque",
    name: "Suite Bosque",
    type: "Suite",
    description: "Retiro elegante en la selva con acceso directo a la naturaleza y amenidades completas",
    bedType: "King",
    maxGuests: 2,
    price: 1400,
    amenities: ["Piscina compartida", "Terraza", "Selva", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/BOSQUE/1.jpg",
      "/images/rooms/BOSQUE/2.jpg",
      "/images/rooms/BOSQUE/3.jpg",
    ],
  },
  {
    id: "musgo",
    name: "Suite Musgo",
    type: "Suite",
    description: "Habitación íntima rodeada de verde, perfecta para parejas",
    bedType: "King",
    maxGuests: 2,
    price: 1200,
    amenities: ["Ducha exterior", "Terraza", "Vistas verdes", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/MUSGO/1.jpg",
      "/images/rooms/MUSGO/2.jpg",
      "/images/rooms/MUSGO/3.jpg",
    ],
  },
  {
    id: "jade",
    name: "Suite Jade",
    type: "Deluxe",
    description: "Lujo contemporáneo en armonía con la naturaleza",
    bedType: "King",
    maxGuests: 2,
    price: 1500,
    amenities: ["Jacuzzi", "Balcón privado", "Minibar", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/JADE/1.jpg",
      "/images/rooms/JADE/2.jpg",
      "/images/rooms/JADE/3.jpg",
    ],
  },
  {
    id: "brote",
    name: "Suite Brote",
    type: "Standard",
    description: "Comodidad y calidez en cada detalle, con vistas frescas",
    bedType: "Twin",
    maxGuests: 2,
    price: 900,
    amenities: ["Ducha privada", "Terraza pequeña", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/BROTE/1.jpg",
      "/images/rooms/BROTE/2.jpg",
      "/images/rooms/BROTE/3.jpg",
    ],
  },
  {
    id: "arena",
    name: "Suite Arena",
    type: "Standard",
    description: "Simpleza elegante, perfecta para viajeros independientes",
    bedType: "King",
    maxGuests: 2,
    price: 950,
    amenities: ["Baño privado", "Aire acondicionado", "WiFi", "Escritorio de trabajo"],
    images: [
      "/images/rooms/ARENA/1.jpg",
      "/images/rooms/ARENA/2.jpg",
      "/images/rooms/ARENA/3.jpg",
    ],
  },
  {
    id: "pergamino",
    name: "Suite Pergamino",
    type: "Comfort",
    description: "Habitación acogedora con carácter tradicional y comodidades modernas",
    bedType: "Twin",
    maxGuests: 2,
    price: 1050,
    amenities: ["Ducha con vista", "Ventiladores", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/PERGAMINO/1.jpg",
      "/images/rooms/PERGAMINO/2.jpg",
      "/images/rooms/PERGAMINO/3.jpg",
    ],
  },
  {
    id: "ambar",
    name: "Suite Ambar",
    type: "Deluxe Family",
    description: "Espacio generoso para familias con comodidades de lujo",
    bedType: "King + Dos Twin",
    maxGuests: 4,
    price: 1600,
    amenities: ["Dos baños", "Sala de estar", "Aire acondicionado", "WiFi", "Microondas"],
    images: [
      "/images/rooms/AMBAR/1.jpg",
      "/images/rooms/AMBAR/2.jpg",
      "/images/rooms/AMBAR/3.jpg",
    ],
  },
  {
    id: "corteza",
    name: "Suite Corteza",
    type: "Suite",
    description: "Cabaña sofisticada con toque rústico y lujos selectos",
    bedType: "King",
    maxGuests: 2,
    price: 1300,
    amenities: ["Chimenea", "Terraza techada", "Ducha privada", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/CORTEZA/1.jpg",
      "/images/rooms/CORTEZA/2.jpg",
      "/images/rooms/CORTEZA/3.jpg",
    ],
  },
  {
    id: "gold",
    name: "Suite Gold",
    type: "Premium",
    description: "La máxima expresión del lujo en Paraiso Encantado",
    bedType: "King + Sofá cama",
    maxGuests: 3,
    price: 1800,
    amenities: ["Jacuzzi privado", "Terraza amplia", "Bar minibar", "Aire acondicionado", "WiFi", "Sala de estar"],
    images: [
      "/images/rooms/GOLD/1.jpg",
      "/images/rooms/GOLD/2.jpg",
      "/images/rooms/GOLD/3.jpg",
    ],
  },
  {
    id: "cascada",
    name: "Suite Cascada",
    type: "Suite Premium",
    description: "Frente a la cascada con sonidos naturales y privacidad absoluta",
    bedType: "King",
    maxGuests: 2,
    price: 1750,
    amenities: ["Vistas a cascada", "Ducha exterior", "Terraza privada", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/CASCADA/1.jpg",
      "/images/rooms/CASCADA/2.jpg",
      "/images/rooms/CASCADA/3.jpg",
    ],
  },
  {
    id: "rio",
    name: "Suite Rio",
    type: "Deluxe",
    description: "A orillas del rio con sonidos naturales constantes",
    bedType: "King",
    maxGuests: 2,
    price: 1450,
    amenities: ["Acceso a rio", "Terraza frente al agua", "Aire acondicionado", "WiFi", "Ducha privada"],
    images: [
      "/images/rooms/RIO/1.jpg",
      "/images/rooms/RIO/2.jpg",
      "/images/rooms/RIO/3.jpg",
    ],
  },
  {
    id: "mirador",
    name: "Suite Mirador",
    type: "Premium Family",
    description: "Punto panorámico único con vistas de 180 grados a la selva",
    bedType: "King + Twin",
    maxGuests: 3,
    price: 1650,
    amenities: ["Terraza panorámica", "Dos baños", "Aire acondicionado", "WiFi", "Minibar"],
    images: [
      "/images/rooms/MIRADOR/1.jpg",
      "/images/rooms/MIRADOR/2.jpg",
      "/images/rooms/MIRADOR/3.jpg",
    ],
  },
  {
    id: "secreto",
    name: "Suite Secreto",
    type: "Intimate Suite",
    description: "Habitación escondida en la naturaleza, solo para dos",
    bedType: "King",
    maxGuests: 2,
    price: 1350,
    amenities: ["Completa privacidad", "Ducha al aire libre", "Terraza cerrada", "Aire acondicionado", "WiFi"],
    images: [
      "/images/rooms/SECRETO/1.jpg",
      "/images/rooms/SECRETO/2.jpg",
      "/images/rooms/SECRETO/3.jpg",
    ],
  },
  {
    id: "eden",
    name: "Suite Eden",
    type: "Family Suite",
    description: "Paraiso dentro del paraiso, ideal para familias extendidas",
    bedType: "2 King + Twin",
    maxGuests: 5,
    price: 1900,
    amenities: ["Piscina privada", "Tres baños", "Sala de estar grande", "Aire acondicionado", "WiFi completo"],
    images: [
      "/images/rooms/EDEN/1.jpg",
      "/images/rooms/EDEN/2.jpg",
      "/images/rooms/EDEN/3.jpg",
    ],
  },
];

// Amenidades principales
export const amenities = [
  {
    id: "piscina-spa",
    name: "Piscina Spa",
    icon: "droplet",
    description: "Piscina climatizada con jacuzzi y área de relajación",
  },
  {
    id: "restaurante",
    name: "El Papán Huasteco",
    icon: "utensils",
    description: "Restaurante gourmet con especialidades de la región",
  },
  {
    id: "wifi",
    name: "WiFi de Alta Velocidad",
    icon: "wifi",
    description: "Internet de fibra óptica en todo el hotel",
  },
  {
    id: "estacionamiento",
    name: "Estacionamiento Privado",
    icon: "car",
    description: "Completo y gratuito para todos los huéspedes",
  },
  {
    id: "naturista",
    name: "Yoga y Meditación",
    icon: "sun",
    description: "Clases diarias en la plataforma natural",
  },
  {
    id: "tours",
    name: "Tours Ecoturísticos",
    icon: "map",
    description: "Excursiones guiadas a cascadas y jardines",
  },
  {
    id: "spa",
    name: "Spa & Masajes",
    icon: "leaf",
    description: "Tratamientos relajantes con productos naturales",
  },
  {
    id: "botanica",
    name: "Jardín Botánico",
    icon: "flower",
    description: "Acceso a la flora única de la Huasteca",
  },
];

// Info del Hotel
export const hotelInfo = {
  name: "Paraiso Encantado",
  tagline: "Tu Casa en la Huasteca",
  description: "Retiro de lujo en plena selva potosina, a 7 minutos del Centro",
  location: {
    city: "Xilitla, San Luis Potosí",
    address: "Carretera Edward James, km 7",
    coordinates: {
      lat: 21.39583,
      lng: -98.63472,
    },
  },
  contact: {
    phone: "+52 (489) 123-4567",
    email: "reservas@paraisoencantado.com",
    whatsapp: "+52 (489) 123-4567",
  },
  hours: {
    checkIn: "15:00",
    checkOut: "12:00",
    reception: "24/7",
  },
  totalRooms: 15,
  yearOpened: 2022,
  features: [
    "Piscina privada en suites selectas",
    "Restaurante El Papán Huasteco",
    "Vistas panorámicas a la selva",
    "Acceso directo a cascadas",
    "Wifi de fibra óptica",
    "Estacionamiento gratuito",
    "Servicios de spa",
    "Tours ecoturísticos",
  ],
};

// Testimonios
export const testimonials = [
  {
    author: "Testimonio Ex-Presidente",
    text: "Un oasis de paz en la selva potosina. La experiencia fue transformadora.",
    rating: 5,
  },
  {
    author: "Visitante Internacional",
    text: "Arquitectura única, naturaleza pura, servicio impecable. Volveré pronto.",
    rating: 5,
  },
  {
    author: "Pareja de Luna de Miel",
    text: "El lugar perfecto para reconectar. Cada detalle está pensado para la comodidad.",
    rating: 5,
  },
];

// Información del Restaurante
export const restaurantInfo = {
  name: "El Papán Huasteco",
  description: "Cocina Huasteca gourmet con ingredientes locales",
  hours: {
    breakfast: "07:00 - 10:00",
    lunch: "12:30 - 16:00",
    dinner: "18:30 - 21:30",
  },
  specialties: [
    "Mixiotes de conejo",
    "Barbacoa tradicional",
    "Enchiladas verdes",
    "Pozole Huasteco",
    "Tamales de rajas",
    "Agua de Jamaica",
  ],
};
